baseurl = "/"
title = "Pete Talbert"
author = "Pete Talbert"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

[taxonomies]
  category = "categories"
  tag = "tags"

googleAnalytics = "UA-130291758-1"
disqusShortname = "petetalbert-rbind-io"
disable_mathjax = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Pete Talbert"
  
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml","sql"]
  highlightjsTheme = "github"
  
  author = "Pete Talbert"
  dateform = "November 2, 2006"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/petetalbert"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/petetalbert"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/petetalbert"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
