baseurl = "https://petetalbert.rbind.io/"
title = "Pete Talbert"
author = "Pete Talbert"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"
paginate = 5

googleAnalytics = "UA-130291758-1"
disqusShortname = "petetalbert-rbind-io"
disable_mathjax = false
summaryLength = 30
disableKinds = ["taxonomy", "section", "taxonomyTerm"]
rssLimit = 10

[taxonomies]
  category = "categories"
  tag = "tags"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Pete Talbert"
  description = "A space to collect my random thoughts and learning in educational data analysis."
  
  highlightjsVersion = "9.13.1"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "sql"]
  highlightjsTheme = "github"
  
  author = "Pete Talbert"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/petetalbert"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
[[menu.main]]
    name = "R-Bloggers"
    url = "https://www.r-bloggers.com/"
    weight = 6